---
title: "case study airbnb"
author: "Longyi Zhao"
date: "2023-10-10"
output: html_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(ggridges)
library(leaflet)
```


## Airbnb data
```{r}

library(p8105.datasets)
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>
  rename(borough = neighbourhood_group) |>
  mutate(stars = review_scores_location/2)
```

## Questions
- Where are Airbnbs expensive? 
  - Borough? Neighborhood?
- Do other factors (room type) affect price?
- How long are Airbnb active?
  - Are airbnbs illegal and do they get shut down
- Which units have the most availablity?
- How is review score impacted by location? 
- How many apts are run by one host? find the same host id


## Do some EDA
```{r}
nyc_airbnb |>
  count(borough)
```

```{r}
nyc_airbnb |>
  group_by(borough, room_type) |>
  summarize(mean_price = mean(price)) |>
  pivot_wider(
    names_from = room_type, 
    values_from = mean_price
  )
```

```{r}
nyc_airbnb |>
  filter(price >= 9500)
```


youwenti 
```{r}
nyc_airbnb |>
  filter(price<1000, room_type=="Entire home/apt") |>
  ggplot(aes(x=price)) +
  geom_histogram() +
  facet_grid(borough~.)
```

```{r}
nyc_airbnb|>
  filter(
    price <1000, 
    room_type == "Entire home/apt", 
    borough == "Manhattan" 
  ) |>
  group_by(neighbourhood) |>
  summarize(
    n_apt = n(), 
    mean_price = mean(price) )|>
  arrange(desc(mean_price))
```

```{r}
nyc_airbnb |>
  filter(
    price <1000, 
    room_type == "Entire home/apt", borough == "Manhattan") |>
  mutate(neighborhood = fct_reorder(neighbourhood, price)) |>
  ggplot(aes(y=neighbourhood, x = price)) +
  geom_density_ridges()
```

## try to make map

```{r}
nyc_airbnb |>
  filter(
    price <1000, 
    room_type == "Entire home/apt", borough == "Manhattan") |>
  ggplot(aes(x=lat, y = long, color = price)) +
  geom_point()
```



```{r}
nyc_airbnb |>
  filter(
    price <1000, 
    room_type == "Entire home/apt", borough == "Manhattan") |>
  sample_n(500) |>
  leaflet() |>
  addTiles() |>
  addCircleMarkers(~lat, ~long, radius = 0.5)
```



```{r}
host_max = which.max(nyc_airbnb$host_id)
```




